cc_library(
  name = "hello_fff",
  srcs = ["hello_fff.cpp"],
  hdrs = ["hello_fff.h"],
  includes = ["."],
  visibility = ["//src/examples/hello_fff/test:__pkg__"],
  deps = ["//src/examples/hello_fff/display"]
)
