
"""Constraint values compilers
Version should be specified, otherwise write none (<name>-<version>)
"""

package(default_visibility = ["//visibility:public"])

CONSTRAINT_SETTING = "//infrastructure/bazel/constraints:compiler"


constraint_value(
    name = "gcc-9.2",
    constraint_setting = CONSTRAINT_SETTING,
)

constraint_value(
    name = "gcc-4.7",
    constraint_setting = CONSTRAINT_SETTING,
)

constraint_value(
    name = "clang-14",
    constraint_setting = CONSTRAINT_SETTING,
)
