cc_binary(
    name = "read_writer",
    srcs = ["read_writer.cpp"],
)

cc_binary(
    name = "read_writer_atomic",
    srcs = ["read_writer_atomic.cpp"],
)

cc_binary(
    name = "read_writer_mutex",
    srcs = ["read_writer_mutex.cpp"],
)

cc_binary(
    name = "read_writer_mutex2",
    srcs = ["read_writer_mutex2.cpp"],
)

cc_binary(
    name = "thread_term",
    srcs = ["thread_term.cpp"],
)
